apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-msapp
  namespace: default
  labels:
    app: nodejs-msapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-msapp
  template:
    metadata:
      labels:
        app: nodejs-msapp
    spec:
      containers:
      - name: nodejs-msapp-container
        image: vlinet2002/nodejs-ms1:v1
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-ms1-service
spec: 
  type: NodePort
  selector: 
    app: nodejs-msapp
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
